# name: technova
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ^3.10.7

# dependencies:
#   flutter:
#     sdk: flutter
# <<<<<<< HEAD
# # =======

#   # UI
# >>>>>>> 520abdc (Update email auth screen , backend  and related changes)
#   cupertino_icons: ^1.0.8
#   flutter_map: ^8.0.0
#   latlong2: ^0.9.1
#   geolocator: ^13.0.2

#   # ğŸ”¥ Firebase core (required)
#   firebase_core: ^3.4.0

#   # ğŸ” Authentication
#   firebase_auth: ^5.2.0
#   google_sign_in: ^6.2.1

#   # ğŸ—„ Firestore database
#   cloud_firestore: ^5.4.0

#   # ğŸŒ Required for Firebase Web (VERY IMPORTANT)
#   firebase_auth_web: ^5.8.13

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
# <<<<<<< HEAD
# =======

# >>>>>>> 520abdc (Update email auth screen , backend  and related changes)
#   flutter_lints: ^6.0.0

# flutter:
#   uses-material-design: true

name: technova
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # Firebase core (required)
  firebase_core: ^3.4.0

  # Authentication
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  firebase_auth_web: ^5.8.13

  # Firestore database
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
