name: technova
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # Firebase core (required)
  firebase_core: ^3.4.0

  # Authentication
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  firebase_auth_web: ^5.8.13

  # ğŸ—„ Firestore database
  cloud_firestore: ^5.4.0

  # ğŸ’¬ SMS & Permissions
  flutter_sms: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/saaya_logo.png
    - assets/images/app_logo.png